### ISSUE TITLE
前端丑爆了， 能不能优化下

### ISSUE THREAD

**Issue by Linsanxian** [szk01/NovelWeb-python-Django#1]
如题

**Comment by szk01** [comment]
你可以试一下。加油


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"LinSanxian"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月26日(星期四) 下午3:59
收件人:&nbsp;"szk01/NovelWeb-python-Django"<NovelWeb-python-Django@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[szk01/NovelWeb-python-Django] 前端丑爆了， 能不能优化下 (#1)




如题

**Comment by Linsanxian** [comment]
把setting.conf push一下

**Comment by szk01** [comment]
没用，数据需要自己爬取。写个样式，你自己可以试试。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"LinSanxian"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月26日(星期四) 下午4:21
收件人:&nbsp;"szk01/NovelWeb-python-Django"<NovelWeb-python-Django@noreply.github.com&gt;;
抄送:&nbsp;"1622391371"<1622391371@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [szk01/NovelWeb-python-Django] 前端丑爆了， 能不能优化下 (#1)




把setting.conf push一下
